// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnaxsktnwsxkdpblnihi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuYXhza3Rud3N4a2RwYmxuaWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDc1NDIsImV4cCI6MjA2OTE4MzU0Mn0.S7RVGcb-17QPtCsXC20-LprmWQx25oQwmL-L2mMBe18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});